apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-sc-mirror
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
provisioner: lvm.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
parameters:
  type: mirror

