kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-raw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-lvm-sc-linear
  volumeMode: Block
  resources:
    requests:
      storage: 100Mi
