kind: Service
apiVersion: v1
metadata:
  name: csi-lvmplugin
  labels:
    app: csi-lvmplugin
spec:
  selector:
    app: csi-lvmplugin
  ports:
    - name: dummy
      port: 12345
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-lvmplugin
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-lvmplugin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-lvmplugin
    spec:
      serviceAccountName: csi-lvmplugin
      containers:
      - args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-lvm/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/csi-lvm /registration/csi-lvm-reg.sock
        name: node-driver-registrar
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
        - mountPath: /csi-data-dir
          name: csi-data-dir
      - args:
        - --drivername=lvm.csi.k8s.io
        - --v=5
        - --endpoint=$(CSI_ENDPOINT)
        - --devices=$(CSI_DEVICESPATTERN)
        - --nodeid=$(KUBE_NODE_NAME)
        - --vgname=$(CSI_VGNAME)
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CSI_DEVICESPATTERN
          value: /dev/loop[0-1]
        - name: CSI_VGNAME
          value: csi-lvm
        image: mwennrich/lvmplugin:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 3
        name: lvm
        ports:
        - containerPort: 9898
          name: healthz
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /var/lib/kubelet/plugins
          mountPropagation: Bidirectional
          name: plugins-dir
        - mountPath: /csi-data-dir
          name: csi-data-dir
        - mountPath: /dev
          name: dev-dir
        - mountPath: /lib/modules
          name: mod-dir
      - args:
        - --csi-address=/csi/csi.sock
        - --health-port=9898
        image: quay.io/k8scsi/livenessprobe:v1.1.0
        imagePullPolicy: IfNotPresent
        name: liveness-probe
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/csi-lvm
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
        name: plugins-dir
      - hostPath:
          path: /var/lib/csi-lvm-data/
          type: DirectoryOrCreate
        name: csi-data-dir
      - hostPath:
          path: /dev
          type: Directory
        name: dev-dir
      - hostPath:
          path: /lib/modules
          type: Directory
        name: mod-dir
