name: "CI job using metal"
on: [pull_request]

jobs:
  cijob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olegtarasov/get-tag@v1
      id: tagName
    - name: Testing
      run: |
        docker login -u mwennrich -p ${{ secrets.DOCKER_HUB_TOKEN }}
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" >> tests/files/.kubeconfig
        make metalci
